language: rust
rust:
  - 1.29.0 # Earliest that's known to work
#  - 1.29.0 # Firefox requirement
  - stable
  - beta
  - nightly
env:
  - RUST_BACKTRACE=1
  - RUST_BACKTRACE=1 ENCODING_RS_LESS_SLOW=1
script:
  - if [[ $ENCODING_RS_LESS_SLOW ]]; then cargo test --verbose --features 'simd-accel less-slow-kanji-encode less-slow-big5-hanzi-encode less-slow-gb-hanzi-encode serde'; fi
  - if [[ -z $ENCODING_RS_LESS_SLOW ]]; then cargo test --verbose; fi
#matrix:
#  allow_failures:
#    - rust: nightly
